### ISSUE TITLE
[Bug]:  Can not deploy SC with "max code size exceeded" error 

### ISSUE THREAD

**Issue by ChefSnoopy** [Uniswap/v4-core#274] opened 2023-06-19 04:20 UTC
### Describe the bug

why i can not deploy this SC in testnet , got max code size exceeded error , even i set runs:0 , still got "max code size exceeded" error 

### Expected Behavior

can deploy SC successfully

**Comment by hensha256** [comment] 2023-07-16 09:02
Duplicate of #200

**Closed by hensha256** 2023-07-16 09:02 UTC
Labels: bug
